### ISSUE TITLE
Please port to Firefox

### ISSUE THREAD

**Issue by andreicristianpetcu** [0ui/gif-scrubber#2]
Hi!
Do you plan to port this to Firefox? It's usually really simple!
https://vimeo.com/241435808

here are the supported APIs https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

Thank you!

**Comment by andreicristianpetcu** [comment]
I published it. If you are interested in taking ownership or sharing ownership, I can do that. https://addons.mozilla.org/en-US/firefox/addon/gifscrubber/

@0ui

**Comment by lonix1** [comment]
@andreicristianpetcu That link is down, is it still available for firefox? Thanks.

**Comment by GeowazM** [comment]
@andreicristianpetcu it would be really helpful if your extention will work on firefox

**Comment by notetiene** [comment]
Any updates on why it was removed?
