### ISSUE TITLE
GIFs no longer loading

### ISSUE THREAD

**Issue by nicolasteetz** [0ui/gif-scrubber#5]
Hello,

The plugin is no longer downloading / displaying GIFs for me:

```
Uncaught RangeError: Invalid typed array length: 2
    at new Uint16Array (<anonymous>)
    at handleGIF (scrubber.js:179)
    at XMLHttpRequest.h.onload (scrubber.js:128)
```

I was using the plugin on ArtStation, but also tried a .gif-file from Wikipedia. I love this plugin, would much appreciate a fix! :)

**Comment by nicolasteetz** [comment]
Alright, this was bothering me a lot – so I looked into it tonight. I don't have any JavaScript knowledge, but I suppose I can read code a little and understand what's going on.

The ArrayBuffer is empty (after the file header) on that website (ArtStation) and coincidentally also on Wikpedia. So I assume what is happening here, is that those sites are stopping the extension from retrieving the whole file via XMLHttpRequest – and instead purposefully return just the header of the file? Is that a thing? Or is it a compatibility issue?

The URL itself is 'clean', directly to the file itself, for example:
https://cdnb.artstation.com/p/assets/images/images/027/236/493/original/nicolas-teetz-teleport-brkdwn-01.gif

**Comment by 0ui** [comment]
Sorry for the delay in addressing this issue. I merged a fix and will release shortly.

I can now load [this example GIF from Wikipedia](https://en.wikipedia.org/wiki/GIF#/media/File:Rotating_earth_(large).gif) which would not load in 4.1.1
<img width="620" alt="Screenshot 2023-07-28 at 12 58 55 AM" src="https://github.com/0ui/gif-scrubber/assets/734006/f89fee35-df9c-481d-b53b-6c6830f784b3">

I can also load the artstation link above.

Thanks for submitting this!
